version: "3.8"
services:
  #  mysql:
  #    image: mysql:8.0
  #    ports:
  #      - "3306:3306"
  ##    command: --default-authentication-plugin=mysql_native_password
  ##    command:
  ##      - "--default-authentication-plugin=mysql_native_password"
  ##      - "--bind-address=0.0.0.0"
  #    command: ["--bind-address=0.0.0.0"]
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: organica
  #      MYSQL_USER: user
  #      MYSQL_PASSWORD: user
  #
  #    volumes:
  #    - ./init:/docker-entrypoint-initdb.d

  mariadb:
    image: mariadb:10.10
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "organica"
      MYSQL_ROOT_PASSWORD: user
    command: ["--bind-address=0.0.0.0"]
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/organica
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: user

  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - mariadb

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
